data_config:
  cand_pool_dir_name: cand_pool/local
  enable_query_instruct: true
  image_size: 224, 224
  query_instruct_path: instructions/query_instructions.tsv
  shuffle_cand: true
  test_dir_name: query/test
  train_dir_name: query/train
  val_dir_name: query/val
dataloader_config:
  batch_size: 1024
  num_workers: 5
dist_config:
  dist_url: env://
embed_config:
  cand_pools_config:
    cand_pools_name_to_embed:
    - visualnews_task0
    - mscoco_task0_test
    - fashion200k_task0
    - webqa_task1
    - edis_task2
    - webqa_task2
    - visualnews_task3
    - mscoco_task3_test
    - fashion200k_task3
    - nights_task4
    - oven_task6
    - infoseek_task6
    - fashioniq_task7
    - cirr_task7
    - oven_task8
    - infoseek_task8
    embed_union_pool: true
    enable_embed: true
  embed_dir_name: embed
  test_datasets_config:
    correspond_cand_pools_name:
    - visualnews_task0
    - mscoco_task0_test
    - fashion200k_task0
    - webqa_task1
    - edis_task2
    - webqa_task2
    - visualnews_task3
    - mscoco_task3_test
    - fashion200k_task3
    - nights_task4
    - oven_task6
    - infoseek_task6
    - fashioniq_task7
    - cirr_task7
    - oven_task8
    - infoseek_task8
    datasets_name:
    - visualnews_task0
    - mscoco_task0
    - fashion200k_task0
    - webqa_task1
    - edis_task2
    - webqa_task2
    - visualnews_task3
    - mscoco_task3
    - fashion200k_task3
    - nights_task4
    - oven_task6
    - infoseek_task6
    - fashioniq_task7
    - cirr_task7
    - oven_task8
    - infoseek_task8
    enable_embed: true
  train_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_embed: false
  use_fp16: true
  val_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_embed: false
experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: UniRAG
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
model:
  alpha: 0.4
  ckpt_config:
    ckpt_dir: checkpoint/${experiment.path_suffix}
    ckpt_name: blip_ff_large.pth
  embed_dim: 768
  image_size: 224
  name: BLIPFeatureFusion
  queue_size: 57960
  short_name: BLIP_FF
  size: Large
  tokenizer_max_length: 100
  vit: large
  vit_ckpt_layer: 12
  vit_grad_ckpt: true
seed: 2023
